"""initial_schema

Revision ID: e41e5a46df95
Revises: 
Create Date: 2026-04-03 14:35:32.364348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41e5a46df95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_risk_concept',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept')
    )
    op.create_table('control',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('FOUNDATION', 'COMMON', 'SPECIALIZED', name='control_tier'), nullable=True),
    sa.Column('is_foundation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('curation_queue_item',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='curation_status'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('division',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metric_source',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('adapter', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulation',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_definition',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier_floor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('taxonomy_term',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('tier_peer_aggregate',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=True),
    sa.Column('peer_count', sa.Integer(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier', 'metric_name')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entra_oid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('entra_oid')
    )
    op.create_table('application',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('division_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_metric_definition',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('control_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('threshold', sa.JSON(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_tags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('control_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('regulation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_assignment',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculated_metric',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('control_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'INSUFFICIENT_DATA', name='kpi_result'), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_calculation_proposal',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('control_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('proposed_value', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposal_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_requirement',
    sa.Column('control_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requirement_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('control_id', 'requirement_id')
    )
    op.create_table('metric_reading',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_interpretation',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requirement_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('layer', sa.Enum('SOURCE', 'SYSTEM', 'USER', name='interpretation_layer'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tier_change_event',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('previous_tier', sa.String(), nullable=True),
    sa.Column('new_tier', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interpretation_divergence_signal',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('interpretation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interpretation_id'], ['risk_interpretation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interpretation_divergence_signal')
    op.drop_table('tier_change_event')
    op.drop_table('risk_interpretation')
    op.drop_table('metric_reading')
    op.drop_table('control_requirement')
    op.drop_table('control_calculation_proposal')
    op.drop_table('calculated_metric')
    op.drop_table('role_assignment')
    op.drop_table('requirement')
    op.drop_table('control_tags')
    op.drop_table('control_metric_definition')
    op.drop_table('application')
    op.drop_table('user')
    op.drop_table('tier_peer_aggregate')
    op.drop_table('taxonomy_term')
    op.drop_table('risk_definition')
    op.drop_table('regulation')
    op.drop_table('metric_source')
    op.drop_table('division')
    op.drop_table('curation_queue_item')
    op.drop_table('control')
    op.drop_table('canonical_risk_concept')
    # ### end Alembic commands ###
